### ISSUE TITLE
Create utility methods 

### ISSUE THREAD

**Issue by mahee2020** [mahendraNiraja/CucumberE2E#25]

**Comment by mahee2020** [comment]
**Following method name :**
doClick() - overwrite webdriver standard method click()
enterText()-overwrite webdriver standard method send key()
do refresh-overwrite webdriver standard method refresh
isElementDisplayed-overwrite webdriver standard  display()
isElementEnabled-overwrite webdriver standard  isenabled()
dragAndDrop-Action Class
rightClick()-Action Class
doubleClick()-Action Class
acceptAlertPopup()- Alert interface
dismissAlertPopup()-Alert interface
selectDropDownByValue()-- Select class 
mouseOver-Action class-
SwitchWindow()-  show handle multiple window 
SwithFrame-Overload by id , name , WebElement
clickElementByJavaScript
getPageTitleByJavaScript
scrollIntoElementByJavaScript
scrollDownPageByJavaScript
scrollUpPageByJavaScript

**Comment by mahendraNiraja** [comment]
done
