### ISSUE TITLE
Sort Time stamp having given date format.

### ISSUE THREAD

**Issue by nirajqa** [mahendraNiraja/CucumberE2E#8]
06/07/2022 12:00 PM
07/07/2022 10:00 AM
07/07/2022 10:00 PM
05/08/2022 11:30 PM

**Comment by mahendraNiraja** [comment]
package com.utils;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class SortDate5 {
	/* Driver Code */
	public static void main(String[] args) {

		List<String> dateStrList = new ArrayList<String>();

		dateStrList.add("06/07/2022 12:00 PM");
		dateStrList.add("07/07/2022 10:00 AM");
		dateStrList.add("07/07/2022 10:00 PM");
		dateStrList.add("05/08/2022 11:30 PM");


		System.out.println("---> Date & Time List Before Sort ");
		for (String dateStr : dateStrList)
			System.out.println(dateStr);

//Sort String Date  
		Collections.sort(dateStrList, new Comparator<String>() {
			DateFormat f = new SimpleDateFormat("MM/dd/yyyy hh:mm aa");

			@Override
			public int compare(String o1, String o2) {
				try {
					return f.parse(o1).compareTo(f.parse(o2));
				} catch (ParseException e) {
					throw new IllegalArgumentException(e);
				}
			}
		});

		System.out.println("---> Date & Time List After Sort ");
		for (String dateStr : dateStrList)
			System.out.println(dateStr);
	}
}

**Comment by mahendraNiraja** [comment]
completed
